install.packages("RPostgreSQL",repos="http://cran.rstudio.com/")
install.packages("data.table",repos="http://cran.rstudio.com/")
install.packages("reshape",repos="http://cran.rstudio.com/")
install.packages("igraph",repos="http://cran.rstudio.com/")
install.packages("jsonlite",repos="http://cran.rstudio.com/")
