install.packages("RPostgreSQL",dependencies=TRUE,repos="http://cran.rstudio.com/")
install.packages("data.table",dependencies=TRUE,repos="http://cran.rstudio.com/")
install.packages("reshape",dependencies=TRUE,repos="http://cran.rstudio.com/")
install.packages("igraph",dependencies=TRUE,repos="http://cran.rstudio.com/")
install.packages("jsonlite",dependencies=TRUE,repos="http://cran.rstudio.com/")
